"""menambah kolom status baterai

Revision ID: 23c1fd8ece41
Revises: 7c8691d45666
Create Date: 2026-06-30 11:43:16.815892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23c1fd8ece41'
down_revision: Union[str, Sequence[str], None] = '7c8691d45666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    op.drop_index(op.f('idx_readings_sensor_id'), table_name='readings')
    op.drop_index(op.f('idx_readings_sensor_time'), table_name='readings')
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_foreign_key(None, 'readings', 'sensors', ['sensor_id'], ['id'])
    op.drop_column('readings', 'created_at')
    op.add_column('sensors', sa.Column('status_baterai', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_column('sensors', 'status_baterai')
    op.add_column('readings', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'readings', type_='foreignkey')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.create_index(op.f('idx_readings_sensor_time'), 'readings', ['sensor_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_readings_sensor_id'), 'readings', ['sensor_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('employees_pkey'))
    )
    # ### end Alembic commands ###
