name: Backend Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Membangun dan Menjalankan Kontainer
      run: docker compose up -d --build

    - name: Periksa Status dan Log Kontainer
      run: |
        docker compose ps
        docker compose logs web

    - name: Menjalankan Pengujian (Pytest)
      run: docker compose exec -T web pytest -v