name: Backend Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Membangun dan Menjalankan Kontainer
      run: docker-compose up -d --build

    - name: Menjalankan Pengujian (Pytest)
      # Parameter -T digunakan agar docker-compose exec bisa berjalan di lingkungan CI (non-interaktif)
      run: docker-compose exec -T web pytest -v